server {
  listen 3108;
  server_name _;

  location / {
    proxy_pass http://host.docker.internal:3101;
    proxy_http_version 1.1;
    proxy_set_header Connection '';
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_read_timeout 180s;
    proxy_send_timeout 180s;
    proxy_buffering off;
    chunked_transfer_encoding on;
  }
}
